### PR TITLE
fix drag gesture direction

### PR DESCRIPTION
**Pull request by rodineijf**
The drag gesture is wrong using flutter 2.5.1

### CODE REVIEW

**Comment by nekocode** [comment]
https://github.com/flutter/flutter/blob/ffb2ecea5223acdd139a5039be2f9c796962833d/packages/flutter/lib/src/cupertino/route.dart#L723

This file was copied from the flutter SDK. It is not mistake/wrong.

**Comment by rodineijf** [comment]
https://user-images.githubusercontent.com/24531420/135642603-3dd7a164-a877-438f-980a-0b4711521797.mov

This is the current behavior that I have using flutter 2.5.1.

May I open an issue to analyze it better?

**Comment by stcojo** [comment]
I have the same issue @nekocode

**Review by stcojo — APPROVED** [review]
please approve this change, thanks

**Comment by AndreiiMorais** [comment]
@nekocode @mohammed7aafar can any of you approve this?

**Pull request closed without merging**
